import {
  Department,
  Position,
  Employee,
  Shift,
  AttendanceRecord,
  RequestForm,
  Payslip,
  Candidate,
  RecruitmentCampaign,
  OKRObjective,
  ASKEvaluation,
  IVANRecord,
} from '@/types';

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'dept-1', code: 'BGD', name: 'Ban Giám Đốc', leaderName: 'Nguyễn Đức Minh', memberCount: 3, description: 'Điều hành chiến lược toàn công ty' },
  { id: 'dept-2', code: 'TECH', name: 'Khối Kỹ Thuật & Công Nghệ', leaderName: 'Lê Việt Thắng', memberCount: 45, description: 'Nghiên cứu & phát triển sản phẩm phần mềm' },
  { id: 'dept-3', code: 'SALES', name: 'Khối Kinh Doanh (Hà Nội & HCM)', leaderName: 'Trần Thị Huệ', memberCount: 32, description: 'Phát triển thị trường & tư vấn giải pháp' },
  { id: 'dept-4', code: 'HR', name: 'Khối Nhân Sự & Hành Chính', leaderName: 'Phạm Thùy Linh', memberCount: 8, description: 'Quản trị nhân lực, C&B, tuyển dụng & đào tạo' },
  { id: 'dept-5', code: 'MKT', name: 'Khối Marketing', leaderName: 'Hoàng Văn Vũ', memberCount: 14, description: 'Thương hiệu, Digital Ads & Growth' },
  { id: 'dept-6', code: 'FIN', name: 'Khối Tài Chính Kế Toán', leaderName: 'Nguyễn Thu Trang', memberCount: 6, description: 'Quản trị tài chính, kế toán & ngân sách' },
];

export const MOCK_POSITIONS: Position[] = [
  { id: 'pos-1', code: 'CEO', title: 'Tổng Giám Đốc (CEO)', departmentId: 'dept-1', level: 'Director', baseSalaryMin: 50000000, baseSalaryMax: 100000000 },
  { id: 'pos-2', code: 'CTO', title: 'Giám Đốc Công Nghệ (CTO)', departmentId: 'dept-2', level: 'Director', baseSalaryMin: 45000000, baseSalaryMax: 80000000 },
  { id: 'pos-3', code: 'HRM', title: 'Trưởng Phòng Nhân Sự (HRM)', departmentId: 'dept-4', level: 'Manager', baseSalaryMin: 25000000, baseSalaryMax: 40000000 },
  { id: 'pos-4', code: 'DEV_SR', title: 'Kỹ Sư Phần Mềm Cao Cấp', departmentId: 'dept-2', level: 'Senior', baseSalaryMin: 25000000, baseSalaryMax: 45000000 },
  { id: 'pos-5', code: 'SALES_LEAD', title: 'Trưởng Nhóm Kinh Doanh', departmentId: 'dept-3', level: 'Lead', baseSalaryMin: 18000000, baseSalaryMax: 35000000 },
  { id: 'pos-6', code: 'HR_CB', title: 'Chuyên Viên C&B & Tiền Lương', departmentId: 'dept-4', level: 'Middle', baseSalaryMin: 12000000, baseSalaryMax: 20000000 },
  { id: 'pos-7', code: 'MKT_DIGITAL', title: 'Chuyên Viên Digital Marketing', departmentId: 'dept-5', level: 'Middle', baseSalaryMin: 12000000, baseSalaryMax: 22000000 },
  { id: 'pos-8', code: 'ACC_GEN', title: 'Kế Toán Tổng Hợp', departmentId: 'dept-6', level: 'Senior', baseSalaryMin: 15000000, baseSalaryMax: 25000000 },
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    code: 'NV-0001',
    fullName: 'Phạm Thùy Linh',
    gender: 'Nữ',
    birthday: '1992-10-22',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    email: 'linh.pham@1hrm.vn',
    phone: '0977 333 833',
    idCard: '001192008765',
    idCardDate: '2018-05-12',
    idCardPlace: 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư',
    address: 'P. Minh Khai, Q. Hai Bà Trưng, TP. Hà Nội',
    nativePlace: 'Hà Nội',
    taxCode: '8025320227',
    socialInsuranceCode: '0120142545',
    bankName: 'MBBank (Ngân hàng Quân đội)',
    bankAccount: '098786857584839',
    bankBranch: 'Chi nhánh Định Công, HN',
    departmentId: 'dept-4',
    departmentName: 'Khối Nhân Sự & Hành Chính',
    positionId: 'pos-3',
    positionTitle: 'Trưởng Phòng Nhân Sự (HRM)',
    role: 'HR_MANAGER',
    joinDate: '2020-03-15',
    contractType: 'Không xác định thời hạn',
    status: 'Đang làm việc',
    baseSalary: 28000000,
    allowance: 3500000,
    workEfficiency: 96,
    completedTasks: 36,
    lateTimes: 0,
    earlyTimes: 0,
    leaveDaysRemaining: 9.5,
    totalLeaveDays: 14,
    assets: [
      { id: 'ast-1', name: 'MacBook Pro M3 14 inch', code: 'TS-MBP-089', assignedDate: '2024-01-10', status: 'Đang sử dụng' },
      { id: 'ast-2', name: 'Màn hình Dell UltraSharp 27 inch', code: 'TS-MH-042', assignedDate: '2023-06-15', status: 'Đang sử dụng' },
    ],
    debts: [],
    workHistory: [
      { period: '2020 - Nay', company: '1HRM Solution JSC', position: 'Trưởng phòng Nhân sự' },
      { period: '2016 - 2020', company: 'Tập đoàn Công nghệ FPT', position: 'HR Team Lead' },
    ],
    contracts: [
      {
        id: 'ctr-1',
        employeeId: 'emp-1',
        contractNumber: 'HĐLĐ-2023/1HRM-001',
        contractType: 'Không xác định thời hạn',
        signedDate: '2023-03-15',
        startDate: '2023-04-01',
        baseSalary: 28000000,
        insuranceSalary: 28000000,
        status: 'Hiệu lực',
        signerName: 'Nguyễn Đức Minh',
        signerPosition: 'Tổng Giám Đốc',
        isSignedDigitally: true,
        signatureProvider: 'Viettel CA',
      }
    ],
    decisions: [
      {
        id: 'dec-1',
        code: 'QĐKT-0057',
        employeeId: 'emp-1',
        employeeName: 'Phạm Thùy Linh',
        type: 'Khen thưởng',
        effectiveDate: '2026-06-30',
        amount: 5000000,
        paymentMethod: 'Cộng vào kỳ lương',
        reason: 'Có thành tích xuất sắc triển khai hệ thống số hóa nhân sự toàn diện',
        issuedBy: 'Nguyễn Đức Minh - Tổng Giám Đốc',
        status: 'Đã duyệt',
      }
    ]
  },
  {
    id: 'emp-2',
    code: 'NV-0002',
    fullName: 'Lê Việt Thắng',
    gender: 'Nam',
    birthday: '1989-04-16',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'thang.le@1hrm.vn',
    phone: '0988 123 456',
    idCard: '001089004321',
    idCardDate: '2017-08-20',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Cầu Giấy, TP. Hà Nội',
    nativePlace: 'Nam Định',
    taxCode: '8025320299',
    socialInsuranceCode: '0120142999',
    bankName: 'MBBank',
    bankAccount: '098786857581111',
    bankBranch: 'Chi nhánh Cầu Giấy',
    departmentId: 'dept-2',
    departmentName: 'Khối Kỹ Thuật & Công Nghệ',
    positionId: 'pos-2',
    positionTitle: 'Giám Đốc Công Nghệ (CTO)',
    role: 'ADMIN',
    joinDate: '2019-11-01',
    contractType: 'Không xác định thời hạn',
    status: 'Đang làm việc',
    baseSalary: 55000000,
    allowance: 5000000,
    workEfficiency: 98,
    completedTasks: 42,
    lateTimes: 1,
    earlyTimes: 0,
    leaveDaysRemaining: 11,
    totalLeaveDays: 15,
    assets: [
      { id: 'ast-3', name: 'MacBook Pro M3 Max 16 inch', code: 'TS-MBP-001', assignedDate: '2024-02-01', status: 'Đang sử dụng' }
    ],
    debts: [],
    workHistory: [
      { period: '2019 - Nay', company: '1HRM Solution JSC', position: 'CTO' },
    ],
    contracts: [],
    decisions: []
  },
  {
    id: 'emp-3',
    code: 'NV-0003',
    fullName: 'Trần Thị Huệ',
    gender: 'Nữ',
    birthday: '1994-08-14',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    email: 'hue.tran@1hrm.vn',
    phone: '0912 456 789',
    idCard: '001194005555',
    idCardDate: '2019-01-10',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Q. Đống Đa, Hà Nội',
    nativePlace: 'Hải Phòng',
    taxCode: '8025320333',
    socialInsuranceCode: '0120143333',
    bankName: 'Vietcombank',
    bankAccount: '0011004567890',
    bankBranch: 'Sở Giao Dịch HN',
    departmentId: 'dept-3',
    departmentName: 'Khối Kinh Doanh (Hà Nội & HCM)',
    positionId: 'pos-5',
    positionTitle: 'Trưởng Nhóm Kinh Doanh',
    role: 'DEPARTMENT_LEAD',
    joinDate: '2021-06-01',
    contractType: 'Có thời hạn 3 năm',
    status: 'Đang làm việc',
    baseSalary: 20000000,
    allowance: 2500000,
    workEfficiency: 105,
    completedTasks: 50,
    lateTimes: 2,
    earlyTimes: 0,
    leaveDaysRemaining: 7,
    totalLeaveDays: 13,
    assets: [
      { id: 'ast-4', name: 'Laptop Dell XPS 15', code: 'TS-XPS-012', assignedDate: '2023-01-10', status: 'Đang sử dụng' }
    ],
    debts: [],
    workHistory: [],
    contracts: [],
    decisions: []
  },
  {
    id: 'emp-4',
    code: 'NV-0004',
    fullName: 'Nguyễn Thu Trang',
    gender: 'Nữ',
    birthday: '1995-12-05',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    email: 'trang.nguyen@1hrm.vn',
    phone: '0966 888 999',
    idCard: '001195009988',
    idCardDate: '2020-03-01',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Q. Hoàng Mai, TP. Hà Nội',
    nativePlace: 'Hà Nội',
    taxCode: '8025320444',
    socialInsuranceCode: '0120144444',
    bankName: 'Techcombank',
    bankAccount: '19034567890123',
    bankBranch: 'Chi nhánh Hoàng Mai',
    departmentId: 'dept-6',
    departmentName: 'Khối Tài Chính Kế Toán',
    positionId: 'pos-8',
    positionTitle: 'Kế Toán Tổng Hợp',
    role: 'EMPLOYEE',
    joinDate: '2022-02-15',
    contractType: 'Có thời hạn 3 năm',
    status: 'Đang làm việc',
    baseSalary: 18000000,
    allowance: 2000000,
    workEfficiency: 92,
    completedTasks: 28,
    lateTimes: 0,
    earlyTimes: 0,
    leaveDaysRemaining: 10,
    totalLeaveDays: 12,
    assets: [],
    debts: [],
    workHistory: [],
    contracts: [],
    decisions: []
  },
  {
    id: 'emp-5',
    code: 'NV-0005',
    fullName: 'Hoàng Văn Vũ',
    gender: 'Nam',
    birthday: '1993-07-19',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    email: 'vu.hoang@1hrm.vn',
    phone: '0904 112 233',
    idCard: '001193007766',
    idCardDate: '2019-11-15',
    idCardPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Q. Ba Đình, TP. Hà Nội',
    nativePlace: 'Bắc Ninh',
    taxCode: '8025320555',
    socialInsuranceCode: '0120145555',
    bankName: 'MBBank',
    bankAccount: '098786857582222',
    bankBranch: 'Chi nhánh Ba Đình',
    departmentId: 'dept-5',
    departmentName: 'Khối Marketing',
    positionId: 'pos-7',
    positionTitle: 'Chuyên Viên Digital Marketing',
    role: 'EMPLOYEE',
    joinDate: '2022-08-01',
    contractType: 'Có thời hạn 1 năm',
    status: 'Đang làm việc',
    baseSalary: 16000000,
    allowance: 1500000,
    workEfficiency: 88,
    completedTasks: 24,
    lateTimes: 3,
    earlyTimes: 1,
    leaveDaysRemaining: 5,
    totalLeaveDays: 12,
    assets: [],
    debts: [],
    workHistory: [],
    contracts: [],
    decisions: []
  }
];

export const MOCK_SHIFTS: Shift[] = [
  { id: 'shift-1', code: 'CA_HC', name: 'Ca Hành Chính', startTime: '08:30', endTime: '17:30', breakStartTime: '12:00', breakEndTime: '13:30', standardWorkUnits: 1.0, type: 'Hành chính' },
  { id: 'shift-2', code: 'CA_SANG', name: 'Ca Sáng (Bán thời gian)', startTime: '08:00', endTime: '12:00', breakStartTime: '12:00', breakEndTime: '12:00', standardWorkUnits: 0.5, type: 'Ca sáng' },
  { id: 'shift-3', code: 'CA_CHIEU', name: 'Ca Chiều (Bán thời gian)', startTime: '13:30', endTime: '17:30', breakStartTime: '17:30', breakEndTime: '17:30', standardWorkUnits: 0.5, type: 'Ca chiều' },
  { id: 'shift-4', code: 'CA_KIP_1', name: 'Ca Kíp Sáng (6h - 14h)', startTime: '06:00', endTime: '14:00', breakStartTime: '11:00', breakEndTime: '11:30', standardWorkUnits: 1.0, type: 'Ca kíp' },
  { id: 'shift-5', code: 'CA_KIP_2', name: 'Ca Kíp Chiều (14h - 22h)', startTime: '14:00', endTime: '22:00', breakStartTime: '18:00', breakEndTime: '18:30', standardWorkUnits: 1.0, type: 'Ca kíp' },
];

export const MOCK_REQUESTS: RequestForm[] = [
  {
    id: 'req-1',
    code: 'DXP-00123',
    type: 'LEAVE',
    typeName: 'Đơn xin nghỉ phép năm',
    employeeId: 'emp-3',
    employeeName: 'Trần Thị Huệ',
    departmentName: 'Khối Kinh Doanh (Hà Nội & HCM)',
    createdAt: '2026-08-20 09:15',
    startDate: '2026-08-28',
    endDate: '2026-08-29',
    durationDays: 2,
    reason: 'Giải quyết việc gia đình',
    approverId: 'emp-1',
    approverName: 'Phạm Thùy Linh (HRM)',
    status: 'APPROVED',
    approvalNote: 'Đã duyệt, công việc bàn giao tốt',
    approvedAt: '2026-08-20 14:30',
    workflowStep: 2,
    workflowMaxSteps: 2,
  },
  {
    id: 'req-2',
    code: 'DOT-00089',
    type: 'OVERTIME',
    typeName: 'Đơn làm thêm giờ (OT)',
    employeeId: 'emp-2',
    employeeName: 'Lê Việt Thắng',
    departmentName: 'Khối Kỹ Thuật & Công Nghệ',
    createdAt: '2026-08-24 16:00',
    startDate: '2026-08-24 18:00',
    endDate: '2026-08-24 21:00',
    durationHours: 3,
    reason: 'Deploy phiên bản Release HRM 2.0 lên Cloud Production',
    approverId: 'emp-1',
    approverName: 'Phạm Thùy Linh',
    status: 'APPROVED',
    approvedAt: '2026-08-24 17:15',
    workflowStep: 2,
    workflowMaxSteps: 2,
  },
  {
    id: 'req-3',
    code: 'DQC-00045',
    type: 'CHECKIN_OUT',
    typeName: 'Đơn giải trình quên check-in',
    employeeId: 'emp-5',
    employeeName: 'Hoàng Văn Vũ',
    departmentName: 'Khối Marketing',
    createdAt: '2026-08-26 08:45',
    startDate: '2026-08-25',
    reason: 'Máy chấm công cửa sảnh 1 bị lỗi kết nối mạng, đã có mặt lúc 08:25',
    approverId: 'emp-1',
    approverName: 'Phạm Thùy Linh',
    status: 'PENDING',
    workflowStep: 1,
    workflowMaxSteps: 2,
  },
  {
    id: 'req-4',
    code: 'DCT-00018',
    type: 'BUSINESS_TRIP',
    typeName: 'Đơn đăng ký công tác',
    employeeId: 'emp-3',
    employeeName: 'Trần Thị Huệ',
    departmentName: 'Khối Kinh Doanh (Hà Nội & HCM)',
    createdAt: '2026-08-25 10:00',
    startDate: '2026-09-02',
    endDate: '2026-09-05',
    durationDays: 4,
    reason: 'Gặp gỡ và ký hợp đồng triển khai giải pháp HRM với đối tác miền Nam',
    approverId: 'emp-1',
    approverName: 'Phạm Thùy Linh',
    status: 'PENDING',
    workflowStep: 1,
    workflowMaxSteps: 2,
  }
];

export const MOCK_PAYSLIPS: Payslip[] = [
  {
    id: 'pay-1',
    employeeId: 'emp-1',
    employeeCode: 'NV-0001',
    employeeName: 'Phạm Thùy Linh',
    departmentName: 'Khối Nhân Sự & Hành Chính',
    month: '08/2026',
    standardDays: 22,
    actualDays: 22,
    otHours: 0,
    baseSalary: 28000000,
    actualBaseSalary: 28000000,
    positionAllowance: 2500000,
    lunchAllowance: 1000000,
    otherAllowance: 0,
    kpiBonus: 4000000,
    commission: 0,
    totalIncome: 35500000,
    socialInsurance: 2240000,
    healthInsurance: 420000,
    unemploymentInsurance: 280000,
    totalInsurance: 2940000,
    taxableIncome: 17060000,
    personalDeduction: 15500000,
    dependentDeduction: 0,
    pitTax: 1206000,
    advancePayment: 0,
    penalties: 0,
    netSalary: 31354000,
    status: 'Đã chốt',
    bankAccount: '098786857584839',
    bankName: 'MBBank',
  },
  {
    id: 'pay-2',
    employeeId: 'emp-2',
    employeeCode: 'NV-0002',
    employeeName: 'Lê Việt Thắng',
    departmentName: 'Khối Kỹ Thuật & Công Nghệ',
    month: '08/2026',
    standardDays: 22,
    actualDays: 22,
    otHours: 6,
    baseSalary: 55000000,
    actualBaseSalary: 55000000,
    positionAllowance: 4000000,
    lunchAllowance: 1000000,
    otherAllowance: 0,
    kpiBonus: 8000000,
    commission: 0,
    totalIncome: 70806818,
    socialInsurance: 3744000,
    healthInsurance: 702000,
    unemploymentInsurance: 550000,
    totalInsurance: 4996000,
    taxableIncome: 44110818,
    personalDeduction: 15500000,
    dependentDeduction: 6200000,
    pitTax: 5322164,
    advancePayment: 0,
    penalties: 0,
    netSalary: 60488654,
    status: 'Đã chốt',
    bankAccount: '098786857581111',
    bankName: 'MBBank',
  },
  {
    id: 'pay-3',
    employeeId: 'emp-3',
    employeeCode: 'NV-0003',
    employeeName: 'Trần Thị Huệ',
    departmentName: 'Khối Kinh Doanh (Hà Nội & HCM)',
    month: '08/2026',
    standardDays: 22,
    actualDays: 21.5,
    otHours: 0,
    baseSalary: 20000000,
    actualBaseSalary: 19545455,
    positionAllowance: 1500000,
    lunchAllowance: 1000000,
    otherAllowance: 0,
    kpiBonus: 6000000,
    commission: 12500000,
    totalIncome: 40545455,
    socialInsurance: 1600000,
    healthInsurance: 300000,
    unemploymentInsurance: 200000,
    totalInsurance: 2100000,
    taxableIncome: 22945455,
    personalDeduction: 15500000,
    dependentDeduction: 0,
    pitTax: 1794546,
    advancePayment: 0,
    penalties: 0,
    netSalary: 36650909,
    status: 'Đã chốt',
    bankAccount: '0011004567890',
    bankName: 'Vietcombank',
  }
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'can-1',
    code: 'UV-0129',
    fullName: 'Vũ Thị Minh Anh',
    email: 'minhanh.vu@gmail.com',
    phone: '0934 567 890',
    campaignId: 'camp-1',
    campaignTitle: 'Tuyển dụng 05 Senior Fullstack React/NodeJS',
    positionApplied: 'Senior Fullstack Engineer',
    appliedDate: '2026-08-20',
    source: 'TopCV',
    aiMatchScore: 94,
    skills: ['React', 'Next.js', 'Node.js', 'PostgreSQL', 'Microservices', 'Docker'],
    experienceYears: 5,
    currentSalary: 30000000,
    expectedSalary: 38000000,
    stage: 'INTERVIEW',
    interviewDate: '2026-08-28 14:00',
    interviewScore: 8.5,
    notes: 'Kinh nghiệm tốt về kiến trúc Microservices, thái độ tích cực',
  },
  {
    id: 'can-2',
    code: 'UV-0130',
    fullName: 'Đỗ Thành Long',
    email: 'long.do@gmail.com',
    phone: '0918 222 333',
    campaignId: 'camp-1',
    campaignTitle: 'Tuyển dụng 05 Senior Fullstack React/NodeJS',
    positionApplied: 'Senior Fullstack Engineer',
    appliedDate: '2026-08-22',
    source: 'LinkedIn',
    aiMatchScore: 91,
    skills: ['Golang', 'Next.js', 'Kubernetes', 'Redis', 'Kafka'],
    experienceYears: 6,
    currentSalary: 35000000,
    expectedSalary: 42000000,
    stage: 'OFFER',
    offerSalary: 40000000,
    notes: 'Đã gửi offer letter qua email, đang chờ phản hồi',
  },
  {
    id: 'can-3',
    code: 'UV-0131',
    fullName: 'Nguyễn Thị Mai',
    email: 'mai.nguyen@gmail.com',
    phone: '0971 888 222',
    campaignId: 'camp-2',
    campaignTitle: 'Tuyển dụng 03 Chuyên viên Tư vấn Doanh nghiệp (B2B Sales)',
    positionApplied: 'B2B Sales Consultant',
    appliedDate: '2026-08-25',
    source: 'Vietnamworks',
    aiMatchScore: 87,
    skills: ['B2B Sales', 'CRM', 'Thuyết trình giải pháp', 'Đàm phán HĐ'],
    experienceYears: 3,
    currentSalary: 15000000,
    expectedSalary: 20000000,
    stage: 'SCREENING',
    notes: 'Hồ sơ đạt yêu cầu, đã hẹn lịch phỏng vấn vòng 1',
  }
];

export const MOCK_CAMPAIGNS: RecruitmentCampaign[] = [
  {
    id: 'camp-1',
    code: 'CD-2026-01',
    title: 'Tuyển dụng 05 Senior Fullstack React/NodeJS',
    departmentId: 'dept-2',
    departmentName: 'Khối Kỹ Thuật & Công Nghệ',
    quantityTarget: 5,
    quantityHired: 2,
    budget: 30000000,
    spentBudget: 12000000,
    startDate: '2026-08-01',
    endDate: '2026-09-30',
    recruiterName: 'Phạm Thùy Linh',
    status: 'Đang chạy',
  },
  {
    id: 'camp-2',
    code: 'CD-2026-02',
    title: 'Tuyển dụng 03 Chuyên viên Tư vấn Doanh nghiệp (B2B Sales)',
    departmentId: 'dept-3',
    departmentName: 'Khối Kinh Doanh (Hà Nội & HCM)',
    quantityTarget: 3,
    quantityHired: 1,
    budget: 15000000,
    spentBudget: 8000000,
    startDate: '2026-08-10',
    endDate: '2026-09-15',
    recruiterName: 'Phạm Thùy Linh',
    status: 'Đang chạy',
  }
];

export const MOCK_OKRS: OKRObjective[] = [
  {
    id: 'okr-1',
    level: 'COMPANY',
    title: 'Mục tiêu Công ty Q3/2026: Tăng trưởng doanh thu 35% & Hoàn thiện nền tảng HRM 2.0',
    ownerName: 'Nguyễn Đức Minh (CEO)',
    quarter: 'Q3/2026',
    progress: 74,
    status: 'On track',
    keyResults: [
      { id: 'kr-1', objectiveId: 'okr-1', title: 'Đạt doanh số ký mới 15 tỷ VNĐ toàn công ty', targetValue: 15000000000, currentValue: 11200000000, unit: 'VND', progress: 75, weight: 40 },
      { id: 'kr-2', objectiveId: 'okr-1', title: 'Phát hành chính thức 10 phân hệ 1HRM cho 100+ khách hàng doanh nghiệp', targetValue: 100, currentValue: 82, unit: 'Doanh nghiệp', progress: 82, weight: 35 },
      { id: 'kr-3', objectiveId: 'okr-1', title: 'Tỷ lệ hài lòng của khách hàng (CSAT) đạt trên 90%', targetValue: 90, currentValue: 88, unit: '%', progress: 97, weight: 25 },
    ]
  },
  {
    id: 'okr-2',
    level: 'DEPARTMENT',
    title: 'Mục tiêu Khối Kỹ Thuật: Tối ưu hiệu năng bộ máy tính công thức (Formula Platform)',
    ownerName: 'Lê Việt Thắng (CTO)',
    departmentName: 'Khối Kỹ Thuật & Công Nghệ',
    quarter: 'Q3/2026',
    progress: 85,
    status: 'On track',
    keyResults: [
      { id: 'kr-4', objectiveId: 'okr-2', title: 'Thời gian tính bảng lương cho 5,000 nhân sự dưới 3 giây', targetValue: 3, currentValue: 2.1, unit: 'giây', progress: 100, weight: 50 },
      { id: 'kr-5', objectiveId: 'okr-2', title: 'Độ phủ kiểm thử tự động (Unit Test Coverage) đạt > 85%', targetValue: 85, currentValue: 72, unit: '%', progress: 84, weight: 50 },
    ]
  },
  {
    id: 'okr-3',
    level: 'DEPARTMENT',
    title: 'Mục tiêu Khối Nhân Sự: Số hóa 100% hồ sơ, hợp đồng và tự động hóa quy trình chấm công',
    ownerName: 'Phạm Thùy Linh (HRM)',
    departmentName: 'Khối Nhân Sự & Hành Chính',
    quarter: 'Q3/2026',
    progress: 90,
    status: 'On track',
    keyResults: [
      { id: 'kr-6', objectiveId: 'okr-3', title: '100% hợp đồng lao động ký số điện tử qua Viettel CA/SmartCA', targetValue: 100, currentValue: 95, unit: '%', progress: 95, weight: 50 },
      { id: 'kr-7', objectiveId: 'okr-3', title: 'Giảm thời gian tổng hợp công cuối tháng từ 3 ngày xuống 30 phút', targetValue: 30, currentValue: 30, unit: 'phút', progress: 100, weight: 50 },
    ]
  }
];

export const MOCK_ASK_EVALUATION: ASKEvaluation = {
  id: 'ask-1',
  employeeId: 'emp-1',
  employeeName: 'Phạm Thùy Linh',
  positionTitle: 'Trưởng Phòng Nhân Sự',
  period: '2026 - Kỳ 1',
  evaluatorName: 'Nguyễn Đức Minh (CEO)',
  averageScore: 4.5,
  grade: 'A - Xuất sắc',
  items: [
    { category: 'Thái độ (Attitude)', criteria: 'Trách nhiệm & Cam kết', requiredScore: 4.0, evaluatedScore: 4.8 },
    { category: 'Thái độ (Attitude)', criteria: 'Tự tin & Quyết đoán', requiredScore: 4.0, evaluatedScore: 4.5 },
    { category: 'Kỹ năng (Skill)', criteria: 'Kỹ năng làm việc nhóm', requiredScore: 3.5, evaluatedScore: 4.2 },
    { category: 'Kỹ năng (Skill)', criteria: 'Tổ chức & Quản trị công việc', requiredScore: 4.0, evaluatedScore: 4.7 },
    { category: 'Kỹ năng (Skill)', criteria: 'Kỹ năng Ngoại ngữ (English)', requiredScore: 3.0, evaluatedScore: 3.8 },
    { category: 'Kỹ năng (Skill)', criteria: 'Kỹ năng Tin học & Phần mềm', requiredScore: 4.0, evaluatedScore: 4.6 },
    { category: 'Kiến thức (Knowledge)', criteria: 'Chuyên môn Luật LĐ & C&B', requiredScore: 4.5, evaluatedScore: 4.9 },
    { category: 'Kiến thức (Knowledge)', criteria: 'Hiểu biết Văn hóa Doanh nghiệp', requiredScore: 4.0, evaluatedScore: 4.5 },
  ],
  strengths: 'Nắm vững luật lao động, kỹ năng quản trị đội ngũ xuất sắc, luôn chủ động cải tiến quy trình.',
  improvements: 'Tiếp tục phát triển thêm kỹ năng phân tích dữ liệu chuyên sâu (HR Analytics & Data BI).'
};

export const MOCK_IVAN_RECORDS: IVANRecord[] = [
  {
    id: 'ivan-1',
    code: 'BHXH-2026-08-01',
    month: '08/2026',
    employeeCode: 'NV-0004',
    employeeName: 'Nguyễn Thu Trang',
    idCard: '001195009988',
    socialInsuranceCode: '0120144444',
    type: 'Điều chỉnh mức đóng',
    oldSalary: 15000000,
    newSalary: 18000000,
    submittedDate: '2026-08-15',
    status: 'Hồ sơ hợp lệ',
    responseNote: 'Cơ quan BHXH TP. Hà Nội đã duyệt và cập nhật sổ BHXH điện tử',
  },
  {
    id: 'ivan-2',
    code: 'BHXH-2026-08-02',
    month: '08/2026',
    employeeCode: 'NV-0005',
    employeeName: 'Hoàng Văn Vũ',
    idCard: '001193007766',
    socialInsuranceCode: '0120145555',
    type: 'Báo tăng mới',
    newSalary: 16000000,
    submittedDate: '2026-08-18',
    status: 'Đã ký số',
    responseNote: 'Đã gửi sang cổng thông tin IVAN Bảo hiểm Xã hội Việt Nam',
  }
];
