import {
  Department,
  Position,
  Employee,
  WorkShift,
  AttendanceRecord,
  HRMRequest,
  Payslip,
  Candidate,
  RecruitmentPlan,
  OKRObjective,
  ASKEvaluation,
  IVANRecord,
  PlantationUnit,
  ProductionTeam,
  TeamAttendanceBatch,
  FieldInspectionCheckIn,
  MonthlyAttendanceSubmission,
  TrainingCourse,
  ComplianceViolation,
} from '@/types';

export const MOCK_DEPARTMENTS: Department[] = [
  { id: 'dept-1', code: 'BGD', name: 'Ban Tổng Giám Đốc', leaderName: 'Lê Việt Thắng', memberCount: 5, description: 'Điều hành chiến lược toàn công ty & các nông trường' },
  { id: 'dept-2', code: 'NT1', name: 'Nông Trường 1 (Bình Phước)', leaderName: 'Nguyễn Văn Hùng (GĐ Nông trường)', memberCount: 320, description: 'Khu vực quản lý 1.250 ha vườn cây cao su khai thác' },
  { id: 'dept-3', code: 'NT2', name: 'Nông Trường 2 (Bình Dương)', leaderName: 'Trần Đình Trọng (GĐ Nông trường)', memberCount: 240, description: 'Khu vực quản lý 980 ha vườn cây cao su thời kỳ cạo' },
  { id: 'dept-4', code: 'NT3', name: 'Nông Trường 3 (Tây Ninh)', leaderName: 'Vũ Quốc Toản (GĐ Nông trường)', memberCount: 380, description: 'Khu vực quản lý 1.450 ha nông trường công nghệ cao' },
  { id: 'dept-5', code: 'HCTH', name: 'Phòng Hành Chính Tổng Hợp & HR', leaderName: 'Phạm Thùy Linh', memberCount: 16, description: 'Quản trị nhân lực, C&B, tổng hợp công & định mức' },
  { id: 'dept-6', code: 'TECH_VP', name: 'Khối Văn Phòng & Kỹ Thuật', leaderName: 'Trần Thị Huệ', memberCount: 45, description: 'Văn phòng điều hành, CNTT & giải pháp số' },
  { id: 'dept-7', code: 'TCKT', name: 'Phòng Tài Chính Kế Toán', leaderName: 'Nguyễn Thu Trang', memberCount: 12, description: 'Tài chính, kế toán & chi trả lương bổng' },
];

export const MOCK_POSITIONS: Position[] = [
  { id: 'pos-1', code: 'CEO', title: 'Tổng Giám Đốc', departmentId: 'dept-1', level: 'Director', baseSalaryMin: 60000000, baseSalaryMax: 120000000 },
  { id: 'pos-2', code: 'NT_DIR', title: 'Giám Đốc Nông Trường', departmentId: 'dept-2', level: 'Manager', baseSalaryMin: 30000000, baseSalaryMax: 50000000 },
  { id: 'pos-3', code: 'HRM', title: 'Trưởng Phòng HCTH / HRM', departmentId: 'dept-5', level: 'Manager', baseSalaryMin: 25000000, baseSalaryMax: 40000000 },
  { id: 'pos-4', code: 'TEAM_LEAD', title: 'Tổ Trưởng Sản Xuất Nông Trường', departmentId: 'dept-2', level: 'Lead', baseSalaryMin: 15000000, baseSalaryMax: 25000000 },
  { id: 'pos-5', code: 'WORKER_CAO', title: 'Công Nhân Cạo Mủ Cao Su', departmentId: 'dept-2', level: 'Junior', baseSalaryMin: 9000000, baseSalaryMax: 18000000 },
  { id: 'pos-6', code: 'OFFICE_STAFF', title: 'Chuyên Viên Khối Văn Phòng', departmentId: 'dept-6', level: 'Middle', baseSalaryMin: 12000000, baseSalaryMax: 22000000 },
  { id: 'pos-7', code: 'ACC_CHIEF', title: 'Kế Toán Trưởng', departmentId: 'dept-7', level: 'Manager', baseSalaryMin: 25000000, baseSalaryMax: 45000000 },
];

export const MOCK_PLANTATIONS: PlantationUnit[] = [
  {
    id: 'plant-1',
    name: 'Nông Trường 1 (Bình Phước)',
    code: 'NT-BP01',
    location: 'Huyện Hớn Quản, Tỉnh Bình Phước',
    directorName: 'Nguyễn Văn Hùng',
    totalHectares: 1250,
    workerCount: 320,
    activeTeamsCount: 8,
  },
  {
    id: 'plant-2',
    name: 'Nông Trường 2 (Bình Dương)',
    code: 'NT-BD02',
    location: 'Huyện Dầu Tiếng, Tỉnh Bình Dương',
    directorName: 'Trần Đình Trọng',
    totalHectares: 980,
    workerCount: 240,
    activeTeamsCount: 6,
  },
  {
    id: 'plant-3',
    name: 'Nông Trường 3 (Tây Ninh)',
    code: 'NT-TN03',
    location: 'Huyện Tân Châu, Tỉnh Tây Ninh',
    directorName: 'Vũ Quốc Toản',
    totalHectares: 1450,
    workerCount: 380,
    activeTeamsCount: 10,
  },
  {
    id: 'plant-4',
    name: 'Khối Văn Phòng Tổng Công Ty',
    code: 'VP-HQ',
    location: 'Tòa nhà Five Star, Kim Giang, Hà Nội & Chi nhánh HCM',
    directorName: 'Lê Việt Thắng (TGĐ)',
    totalHectares: 0,
    workerCount: 78,
    activeTeamsCount: 4,
  },
];

export const MOCK_PRODUCTION_TEAMS: ProductionTeam[] = [
  {
    id: 'team-1',
    name: 'Tổ Khai Thác 1 - Nông Trường 1',
    code: 'TO-01-NT1',
    plantationId: 'plant-1',
    plantationName: 'Nông Trường 1 (Bình Phước)',
    leaderId: 'emp-tt-1',
    leaderName: 'Nguyễn Văn Lực (Tổ Trưởng)',
    lotAssigned: 'Lô A1 - Lô A6 (Cây 10 năm)',
    lotAreaHectares: 48.5,
    memberCount: 42,
  },
  {
    id: 'team-2',
    name: 'Tổ Khai Thác 2 - Nông Trường 1',
    code: 'TO-02-NT1',
    plantationId: 'plant-1',
    plantationName: 'Nông Trường 1 (Bình Phước)',
    leaderId: 'emp-tt-2',
    leaderName: 'Lê Văn Thành (Tổ Trưởng)',
    lotAssigned: 'Lô B1 - Lô B8 (Cây 12 năm)',
    lotAreaHectares: 52.0,
    memberCount: 40,
  },
];

export const MOCK_TEAM_ATTENDANCE_BATCHES: TeamAttendanceBatch[] = [
  {
    id: 'batch-001',
    date: '02/09/2026',
    teamId: 'team-1',
    teamName: 'Tổ Khai Thác 1 - Nông Trường 1',
    plantationId: 'plant-1',
    plantationName: 'Nông Trường 1 (Bình Phước)',
    leaderId: 'emp-tt-1',
    leaderName: 'Nguyễn Văn Lực (Tổ Trưởng)',
    totalMembers: 42,
    presentCount: 40,
    leaveCount: 1,
    absentCount: 0,
    coveredCount: 1,
    totalLotAreaHectares: 48.5,
    totalLatexYieldKg: 1740.5,
    avgTscDegree: 34.4,
    isOfflineSync: false,
    status: 'APPROVED_SUPERVISOR',
    supervisorComment: 'Đã kiểm tra đối soát sản lượng lô A1-A6. Khối lượng và chất lượng mủ đạt tiêu chuẩn.',
    approvedAt: '02/09/2026 10:45 AM',
    items: [
      { workerId: 'w-1', workerCode: 'CN-0101', workerName: 'Trần Văn Mạnh', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80', lotAssigned: 'Lô A1', status: 'DU', latexYieldKg: 42.5, cupLumpYieldKg: 6.2, tscDegree: 34.2 },
      { workerId: 'w-2', workerCode: 'CN-0102', workerName: 'Lê Thị Mai', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80', lotAssigned: 'Lô A1', status: 'DU', latexYieldKg: 45.0, cupLumpYieldKg: 7.0, tscDegree: 35.1 },
      { workerId: 'w-3', workerCode: 'CN-0103', workerName: 'Hoàng Văn Phúc', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80', lotAssigned: 'Lô A2', status: 'NGHI_PHEP', note: 'Nghỉ phép năm 1 ngày có đơn' },
      { workerId: 'w-4', workerCode: 'CN-0104', workerName: 'Nguyễn Thị Tuyết', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80', lotAssigned: 'Lô A2 (Choàng thêm Lô A2 của Phúc)', status: 'CHOANG_LO', coveredForWorkerName: 'Hoàng Văn Phúc', latexYieldKg: 78.5, cupLumpYieldKg: 12.0, tscDegree: 34.5 },
      { workerId: 'w-5', workerCode: 'CN-0105', workerName: 'Phạm Đình Dũng', avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80', lotAssigned: 'Lô A3', status: 'DU', latexYieldKg: 41.0, cupLumpYieldKg: 5.8, tscDegree: 34.0 },
      { workerId: 'w-6', workerCode: 'CN-0106', workerName: 'Bùi Thị Hà', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80', lotAssigned: 'Lô A3', status: 'DU', latexYieldKg: 43.5, cupLumpYieldKg: 6.5, tscDegree: 35.0 },
      { workerId: 'w-7', workerCode: 'CN-0107', workerName: 'Đỗ Văn Cường', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80', lotAssigned: 'Lô A4', status: 'DU', latexYieldKg: 39.8, cupLumpYieldKg: 6.0, tscDegree: 33.5 },
      { workerId: 'w-8', workerCode: 'CN-0108', workerName: 'Vũ Thị Ngọc', avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=120&auto=format&fit=crop&q=80', lotAssigned: 'Lô A4', status: 'DU', latexYieldKg: 46.2, cupLumpYieldKg: 7.2, tscDegree: 35.4 },
    ]
  }
];

export const MOCK_FIELD_INSPECTIONS: FieldInspectionCheckIn[] = [
  {
    id: 'insp-1',
    date: '02/09/2026',
    supervisorId: 'emp-gdnt-1',
    supervisorName: 'Nguyễn Văn Hùng (GĐ Nông Trường 1)',
    plantationId: 'plant-1',
    plantationName: 'Nông Trường 1 (Bình Phước)',
    lotChecked: 'Lô A1 - A5 (Tổ 1 & Tổ 2)',
    gpsCoordinates: '11.4582° N, 106.8921° E',
    distanceMeters: 18,
    photoUrl: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=400&auto=format&fit=crop&q=80',
    notes: 'Kiểm tra đường cạo đúng độ sâu dăm, mủ chảy đều, công nhân trang bị đầy đủ BHLĐ.',
    timestamp: '07:35 AM',
    approvedTeamsCount: 2,
  }
];

export const MOCK_MONTHLY_SUBMISSIONS: MonthlyAttendanceSubmission[] = [
  {
    id: 'sub-08-2026',
    month: '08/2026',
    title: 'Tờ trình Tổng hợp Công & Sản lượng mủ Tháng 08/2026 (Chuyển tính lương)',
    submittedBy: 'Phạm Thùy Linh (Trưởng Phòng HCTH)',
    submittedDate: '01/09/2026',
    totalEmployees: 1018,
    totalWorkdays: 24.2,
    plantationSummary: [
      { plantationName: 'Nông Trường 1 (Bình Phước)', totalWorkers: 320, actualDaysAvg: 24.5, totalLatexYieldTons: 485.2, status: 'Đã đối soát 100%' },
      { plantationName: 'Nông Trường 2 (Bình Dương)', totalWorkers: 240, actualDaysAvg: 23.8, totalLatexYieldTons: 362.0, status: 'Đã đối soát 100%' },
      { plantationName: 'Nông Trường 3 (Tây Ninh)', totalWorkers: 380, actualDaysAvg: 24.1, totalLatexYieldTons: 540.8, status: 'Đã đối soát 100%' },
      { plantationName: 'Khối Văn Phòng Tổng Công Ty', totalWorkers: 78, actualDaysAvg: 24.8, totalLatexYieldTons: 0, status: 'FaceID & Chấm công máy' },
    ],
    isApprovedByExecutive: true,
    executiveApproverName: 'Lê Việt Thắng (Tổng Giám Đốc)',
    approvedAt: '02/09/2026 14:20 PM',
  }
];

// -------------------------------------------------------------
// EMPLOYEES VỚI PROFILE COMPLETENESS & CẢNH BÁO HỒ SƠ
// -------------------------------------------------------------

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    code: 'NV-0001',
    fullName: 'Phạm Thùy Linh',
    gender: 'Nữ',
    birthday: '1992-10-22',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    email: 'linh.pham@1hrm.vn',
    phone: '0977 333 833',
    idCard: '001192008765',
    idCardDate: '2018-05-12',
    idCardPlace: 'Cục Cảnh sát ĐKQL cư trú và DLQG về dân cư',
    address: 'P. Minh Khai, Q. Hai Bà Trưng, TP. Hà Nội',
    nativePlace: 'Hà Nội',
    taxCode: '8025320227',
    socialInsuranceCode: '0120142545',
    bankName: 'MBBank (Ngân hàng Quân đội)',
    bankAccount: '098786857584839',
    bankBranch: 'Chi nhánh Định Công, HN',
    departmentId: 'dept-5',
    departmentName: 'Phòng Hành Chính Tổng Hợp & HR',
    positionId: 'pos-3',
    positionTitle: 'Trưởng Phòng HCTH / HRM',
    role: 'HR_MANAGER',
    joinDate: '2020-03-15',
    contractType: 'Không xác định thời hạn',
    status: 'Đang làm việc',
    baseSalary: 28000000,
    allowance: 4500000,
    workEfficiency: 96,
    completedTasks: 48,
    lateTimes: 0,
    earlyTimes: 0,
    leaveDaysRemaining: 10,
    totalLeaveDays: 12,
    age: 34,
    education: 'Đại học',
    seniorityYears: 6,
    profileCompleteness: 100,
    isProfileComplete: true,
    missingDocuments: [],
    assets: [],
    debts: [],
    workHistory: [],
    contracts: [],
    decisions: []
  },
  {
    id: 'emp-2',
    code: 'NV-0002',
    fullName: 'Lê Việt Thắng',
    gender: 'Nam',
    birthday: '1988-04-15',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'thang.le@1hrm.vn',
    phone: '0912 888 999',
    idCard: '001088001234',
    idCardDate: '2016-08-20',
    idCardPlace: 'Cục CS QLHC về TTXH',
    address: 'KĐT Ciputra, Tây Hồ, Hà Nội',
    nativePlace: 'Hà Nội',
    taxCode: '8025320228',
    socialInsuranceCode: '0120142546',
    bankName: 'Techcombank',
    bankAccount: '19033445566778',
    bankBranch: 'Hội sở chính Techcombank',
    departmentId: 'dept-1',
    departmentName: 'Ban Tổng Giám Đốc',
    positionId: 'pos-1',
    positionTitle: 'Tổng Giám Đốc (CEO)',
    role: 'ADMIN',
    joinDate: '2019-01-01',
    contractType: 'Không xác định thời hạn',
    status: 'Đang làm việc',
    baseSalary: 65000000,
    allowance: 15000000,
    workEfficiency: 98,
    completedTasks: 62,
    lateTimes: 0,
    earlyTimes: 0,
    leaveDaysRemaining: 12,
    totalLeaveDays: 12,
    age: 38,
    education: 'Thạc sĩ / Sau ĐH',
    seniorityYears: 7,
    profileCompleteness: 100,
    isProfileComplete: true,
    missingDocuments: [],
    assets: [],
    debts: [],
    workHistory: [],
    contracts: [],
    decisions: []
  },
  {
    id: 'emp-3',
    code: 'NV-0003',
    fullName: 'Trần Thị Huệ',
    gender: 'Nữ',
    birthday: '1995-08-19',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    email: 'hue.tran@1hrm.vn',
    phone: '0983 456 789',
    idCard: '001195009876',
    idCardDate: '2019-11-10',
    idCardPlace: 'Cục CS QLHC về TTXH',
    address: 'Đống Đa, Hà Nội',
    nativePlace: 'Hải Phòng',
    taxCode: '8025320229',
    socialInsuranceCode: '0120142547',
    bankName: 'Vietcombank',
    bankAccount: '0011004567890',
    bankBranch: 'Chi nhánh Ba Đình',
    departmentId: 'dept-6',
    departmentName: 'Khối Văn Phòng & Kỹ Thuật',
    positionId: 'pos-6',
    positionTitle: 'Trưởng Khối Văn Phòng',
    role: 'DEPARTMENT_LEAD',
    joinDate: '2021-06-01',
    contractType: 'Có thời hạn 3 năm',
    status: 'Đang làm việc',
    baseSalary: 22000000,
    allowance: 3000000,
    workEfficiency: 92,
    completedTasks: 35,
    lateTimes: 1,
    earlyTimes: 0,
    leaveDaysRemaining: 8,
    totalLeaveDays: 12,
    age: 31,
    education: 'Đại học',
    seniorityYears: 5,
    profileCompleteness: 75,
    isProfileComplete: false,
    missingDocuments: ['Giấy khám sức khỏe định kỳ 2026', 'Ảnh thẻ 3x4'],
    assets: [],
    debts: [],
    workHistory: [],
    contracts: [],
    decisions: []
  },
  {
    id: 'emp-4',
    code: 'NV-0004',
    fullName: 'Nguyễn Văn Minh (Onboard Mới)',
    gender: 'Nam',
    birthday: '1998-05-14',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    email: 'minh.nguyen@1hrm.vn',
    phone: '0908 777 666',
    idCard: '070098001122',
    idCardDate: '2020-03-10',
    idCardPlace: 'Công an Tỉnh Bình Phước',
    address: 'Hớn Quản, Bình Phước',
    nativePlace: 'Bình Phước',
    taxCode: '8025320235',
    socialInsuranceCode: '',
    bankName: 'Agribank',
    bankAccount: '5600205999888',
    bankBranch: 'Chi nhánh Hớn Quản',
    departmentId: 'dept-2',
    departmentName: 'Nông Trường 1 (Bình Phước)',
    positionId: 'pos-5',
    positionTitle: 'Kỹ Sư Nông Nghiệp & Quản Lý Lô Cạo',
    role: 'EMPLOYEE',
    joinDate: '2026-08-15',
    contractType: 'Thử việc 2 tháng',
    status: 'Thử việc',
    baseSalary: 16000000,
    allowance: 2500000,
    workEfficiency: 88,
    completedTasks: 10,
    lateTimes: 0,
    earlyTimes: 0,
    leaveDaysRemaining: 12,
    totalLeaveDays: 12,
    age: 28,
    education: 'Đại học',
    seniorityYears: 0,
    profileCompleteness: 60,
    isProfileComplete: false,
    missingDocuments: ['Bản sao Bằng tốt nghiệp Đại học', 'Sổ Bảo Hiểm Xã Hội gốc', 'Giấy khám sức khỏe'],
    assets: [],
    debts: [],
    workHistory: [],
    contracts: [],
    decisions: []
  }
];

// -------------------------------------------------------------
// ĐẦY ĐỦ CÁC LOẠI ĐƠN TỪ PHÁT SINH (SUREHCS STANDARD)
// -------------------------------------------------------------

export const MOCK_REQUESTS: HRMRequest[] = [
  {
    id: 'req-1',
    code: 'ĐƠN-DM01',
    employeeId: 'emp-3',
    employeeName: 'Trần Thị Huệ',
    employeeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    departmentName: 'Khối Văn Phòng & Kỹ Thuật',
    type: 'DI_MUON',
    typeName: 'Đơn giải trình đi muộn',
    startDate: '2026-09-02',
    durationDays: 0,
    durationHours: 0.5,
    lateMinutes: 25,
    reason: 'Kẹt xe đường Nguyễn Trãi do mưa ngập buổi sáng',
    specificDetails: 'Đi muộn 25 phút (Vào lúc 08:55 AM)',
    status: 'APPROVED',
    approverName: 'Phạm Thùy Linh',
    createdAt: '2026-09-02 09:05',
  },
  {
    id: 'req-2',
    code: 'ĐƠN-VS02',
    employeeId: 'emp-4',
    employeeName: 'Nguyễn Văn Minh',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    departmentName: 'Nông Trường 1 (Bình Phước)',
    type: 'VE_SOM',
    typeName: 'Đơn xin về sớm',
    startDate: '2026-09-01',
    durationDays: 0,
    durationHours: 1,
    earlyMinutes: 60,
    reason: 'Có lịch hẹn làm thủ tục công chứng nhà đất',
    specificDetails: 'Về sớm 60 phút (Rời lô cạo lúc 16:30)',
    status: 'APPROVED',
    approverName: 'Nguyễn Văn Hùng (GĐ Nông Trường)',
    createdAt: '2026-09-01 14:00',
  },
  {
    id: 'req-3',
    code: 'ĐƠN-CO03',
    employeeId: 'emp-1',
    employeeName: 'Phạm Thùy Linh',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    departmentName: 'Phòng Hành Chính Tổng Hợp & HR',
    type: 'CON_OM',
    typeName: 'Đơn nghỉ chế độ con ốm (BHXH)',
    startDate: '2026-08-25',
    endDate: '2026-08-26',
    durationDays: 2,
    childName: 'Lê Gia Hưng',
    childAge: 3,
    hospitalCertCode: 'BV-NHI-C65-88992',
    reason: 'Chăm sóc con nhỏ 3 tuổi bị sốt virus điều trị tại BV Nhi Trung Ương',
    specificDetails: 'Con: Lê Gia Hưng (3 tuổi) | Giấy viện C65-HD: BV-NHI-C65-88992',
    status: 'APPROVED',
    approverName: 'Lê Việt Thắng (TGĐ)',
    createdAt: '2026-08-24 18:30',
  },
  {
    id: 'req-4',
    code: 'ĐƠN-OM04',
    employeeId: 'emp-tt-1',
    employeeName: 'Nguyễn Văn Lực (Tổ Trưởng)',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    departmentName: 'Nông Trường 1 (Bình Phước)',
    type: 'OM_DAU',
    typeName: 'Đơn nghỉ ốm đau bản thân',
    startDate: '2026-08-20',
    endDate: '2026-08-21',
    durationDays: 2,
    hospitalCertCode: 'TTYT-HQ-99882',
    reason: 'Sốt xuất huyết điều trị tại TTYT Huyện Hớn Quản',
    specificDetails: 'Giấy chứng nhận nghỉ việc hưởng BHXH số TTYT-HQ-99882',
    status: 'APPROVED',
    approverName: 'Nguyễn Văn Hùng',
    createdAt: '2026-08-19 20:00',
  },
  {
    id: 'req-5',
    code: 'ĐƠN-PN05',
    employeeId: 'emp-3',
    employeeName: 'Trần Thị Huệ',
    employeeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    departmentName: 'Khối Văn Phòng & Kỹ Thuật',
    type: 'PHEP_NAM',
    typeName: 'Đơn xin nghỉ phép năm',
    startDate: '2026-08-28',
    endDate: '2026-08-28',
    durationDays: 1,
    reason: 'Nghỉ giải quyết việc gia đình cá nhân',
    specificDetails: 'Trừ vào quỹ phép năm 2026 (Còn 8 ngày)',
    status: 'PENDING',
    createdAt: '2026-08-27 09:30',
  },
  {
    id: 'req-6',
    code: 'ĐƠN-CT06',
    employeeId: 'emp-1',
    employeeName: 'Phạm Thùy Linh',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    departmentName: 'Phòng Hành Chính Tổng Hợp & HR',
    type: 'CONG_TAC',
    typeName: 'Đơn đăng ký công tác nông trường',
    startDate: '2026-09-05',
    endDate: '2026-09-07',
    durationDays: 3,
    tripDestination: 'Nông Trường 1 (Bình Phước) & Nông Trường 2 (Bình Dương)',
    reason: 'Kiểm tra thực địa định mức cạo mủ và hướng dẫn cài đặt app 1HRM cho các Tổ trưởng',
    specificDetails: 'Điểm đến: NT1 & NT2 | Phương tiện: Xe công vụ',
    status: 'APPROVED',
    approverName: 'Lê Việt Thắng (TGĐ)',
    createdAt: '2026-09-01 11:00',
  },
  {
    id: 'req-7',
    code: 'ĐƠN-OT07',
    employeeId: 'emp-4',
    employeeName: 'Nguyễn Văn Minh',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    departmentName: 'Nông Trường 1 (Bình Phước)',
    type: 'LAM_THEM_GIO',
    typeName: 'Đơn đăng ký làm thêm giờ (OT)',
    startDate: '2026-08-30',
    durationDays: 0,
    durationHours: 4,
    overtimeHours: 4,
    reason: 'Hỗ trợ trạm thu mua mủ nước số 2 phân loại và cân mủ vào ca đêm',
    specificDetails: 'OT Ca đêm: 4 giờ (Hưởng 200% lương theo Luật)',
    status: 'APPROVED',
    approverName: 'Nguyễn Văn Hùng',
    createdAt: '2026-08-29 16:30',
  }
];

export const MOCK_PAYSLIPS: Payslip[] = [
  {
    id: 'ps-1',
    month: '08/2026',
    employeeId: 'emp-1',
    employeeCode: 'NV-0001',
    employeeName: 'Phạm Thùy Linh',
    departmentName: 'Phòng Hành Chính Tổng Hợp & HR',
    positionTitle: 'Trưởng Phòng HCTH / HRM',
    standardDays: 24,
    actualDays: 24,
    baseSalary: 28000000,
    actualBaseSalary: 28000000,
    positionAllowance: 3000000,
    lunchAllowance: 1500000,
    kpiBonus: 5000000,
    commission: 0,
    totalIncome: 37500000,
    socialInsuranceEmp: 2240000,
    healthInsuranceEmp: 420000,
    unemploymentInsuranceEmp: 280000,
    totalInsurance: 2940000,
    taxableIncome: 36000000,
    personalDeduction: 15500000,
    dependentDeduction: 0,
    taxAssessableIncome: 17560000,
    pitTax: 1256000,
    netSalary: 33304000,
    status: 'Đã thanh toán',
  },
  {
    id: 'ps-2',
    month: '08/2026',
    employeeId: 'emp-2',
    employeeCode: 'NV-0002',
    employeeName: 'Lê Việt Thắng',
    departmentName: 'Ban Tổng Giám Đốc',
    positionTitle: 'Tổng Giám Đốc (CEO)',
    standardDays: 24,
    actualDays: 24,
    baseSalary: 65000000,
    actualBaseSalary: 65000000,
    positionAllowance: 10000000,
    lunchAllowance: 1500000,
    kpiBonus: 12000000,
    commission: 0,
    totalIncome: 88500000,
    socialInsuranceEmp: 3744000,
    healthInsuranceEmp: 702000,
    unemploymentInsuranceEmp: 468000,
    totalInsurance: 4914000,
    taxableIncome: 87000000,
    personalDeduction: 15500000,
    dependentDeduction: 6200000,
    taxAssessableIncome: 60386000,
    pitTax: 8615800,
    netSalary: 74970200,
    status: 'Đã thanh toán',
  }
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'can-1',
    fullName: 'Hoàng Quốc Việt',
    email: 'viet.hoang@gmail.com',
    phone: '0912 345 678',
    idCard: '070099008877',
    birthday: '1999-07-20',
    gender: 'Nam',
    address: 'Dầu Tiếng, Bình Dương',
    positionTitle: 'Kỹ Sư Nông Nghiệp & Quản Lý Lô Cạo',
    departmentName: 'Nông Trường 2 (Bình Dương)',
    experienceYears: 4,
    expectedSalary: 16000000,
    stage: 'OFFER',
    aiMatchScore: 94,
    source: 'Giới thiệu nội bộ',
    appliedDate: '2026-08-20',
  },
  {
    id: 'can-2',
    fullName: 'Đặng Thị Thanh Hằng',
    email: 'hang.dang@gmail.com',
    phone: '0978 999 888',
    idCard: '001198005544',
    birthday: '1998-11-12',
    gender: 'Nữ',
    address: 'Hà Nội',
    positionTitle: 'Chuyên Viên C&B & Tiền Lương',
    departmentName: 'Phòng Hành Chính Tổng Hợp & HR',
    experienceYears: 3,
    expectedSalary: 15000000,
    stage: 'INTERVIEW',
    aiMatchScore: 91,
    source: 'Website 1HRM',
    appliedDate: '2026-08-25',
  }
];

export const MOCK_RECRUITMENT_PLANS: RecruitmentPlan[] = [
  {
    id: 'rec-plan-1',
    code: 'TD-NT1-Q3',
    title: 'Tuyển Dụng Công Nhân Cạo Mủ Nông Trường 1',
    departmentId: 'dept-2',
    departmentName: 'Nông Trường 1 (Bình Phước)',
    quantityTarget: 30,
    quantityHired: 28,
    budget: 45000000,
    spentBudget: 42000000,
    startDate: '2026-07-01',
    endDate: '2026-09-30',
    recruiterName: 'Phạm Thùy Linh',
    status: 'Đang chạy',
  }
];

export const MOCK_OKRS: OKRObjective[] = [
  {
    id: 'okr-1',
    level: 'COMPANY',
    title: 'Đạt Sản Lượng 1.500 Tấn Mủ Cao Su & Tối Ưu Năng Suất Thu Hoạch Q3/2026',
    ownerName: 'Lê Việt Thắng (Tổng Giám Đốc)',
    quarter: 'Q3/2026',
    progress: 82,
    status: 'On track',
    keyResults: [
      { id: 'kr-1', objectiveId: 'okr-1', title: 'Tổng sản lượng mủ quy khô giao nộp toàn 3 nông trường', targetValue: 1500, currentValue: 1388, unit: 'Tấn', progress: 92, weight: 50 },
      { id: 'kr-2', objectiveId: 'okr-1', title: 'Tỷ lệ chấm công mobile 1-chạm & định vị lô cạo đúng chuẩn', targetValue: 100, currentValue: 98.6, unit: '%', progress: 98, weight: 30 },
      { id: 'kr-3', objectiveId: 'okr-1', title: 'Tỷ lệ hao hụt mặt cạo và vi phạm quy trình kỹ thuật', targetValue: 2, currentValue: 1.2, unit: '%', progress: 85, weight: 20 },
    ]
  }
];

export const MOCK_IVAN_RECORDS: IVANRecord[] = [
  {
    id: 'ivan-1',
    code: 'BH-2026-0801',
    month: '08/2026',
    employeeCode: 'NV-0001',
    employeeName: 'Phạm Thùy Linh',
    idCard: '001192008765',
    socialInsuranceCode: '0120142545',
    type: 'Điều chỉnh mức đóng',
    oldSalary: 25000000,
    newSalary: 28000000,
    submittedDate: '2026-08-20',
    status: 'Hồ sơ hợp lệ',
    responseNote: 'Cơ quan BHXH TP. Hà Nội đã duyệt'
  }
];

export const MOCK_TRAINING_COURSES: TrainingCourse[] = [
  {
    id: 'tc-1',
    code: 'DT-CAO-01',
    title: 'Kỹ Thuật Cạo Mủ Cao Su Chuẩn Quốc Tế & Bảo Vệ Mặt Cạo',
    topic: 'Kỹ thuật khai thác mủ nông trường',
    method: 'Hiện trường nông trường',
    durationHours: 32,
    startDate: '10/08/2026',
    endDate: '15/08/2026',
    participantsCount: 145,
    totalCost: 72500000,
    costPerParticipant: 500000,
    trainerName: 'Chuyên gia Nông Nghiệp ThS. Đỗ Văn Lâm',
    feedbackScore: 4.9,
    examPassRate: 98,
    applicationLevel: 'Rất cao (90-100%)',
    status: 'Đã hoàn thành',
  }
];

export const MOCK_COMPLIANCE_DATA = {
  onTimeRate: 97.4,
  attendanceComplianceRate: 98.6,
  totalViolationsMonth: 26,
  totalWarnings: 18,
  totalDisciplined: 8,
  byPlantationCompliance: [
    { name: 'Nông Trường 1', onTime: 98.2, compliance: 99.1, violations: 5 },
    { name: 'Nông Trường 3', onTime: 97.5, compliance: 98.4, violations: 9 },
    { name: 'Nông Trường 2', onTime: 96.8, compliance: 97.8, violations: 8 },
    { name: 'Khối Văn Phòng', onTime: 97.1, compliance: 99.0, violations: 4 },
  ],
  violationsList: [
    { id: 'v-1', code: 'VP-001', employeeName: 'Trần Văn Bình', departmentOrPlantation: 'Tổ 2 - Nông Trường 1', date: '28/08/2026', type: 'Vi phạm kỹ thuật cạo mủ', disciplineForm: 'Nhắc nhở nội bộ', status: 'Đã xử lý' },
    { id: 'v-2', code: 'VP-002', employeeName: 'Lê Hoàng Nam', departmentOrPlantation: 'Tổ 4 - Nông Trường 2', date: '25/08/2026', type: 'Không đội mũ BHLĐ', disciplineForm: 'Nhắc nhở nội bộ', status: 'Đã xử lý' },
  ] as ComplianceViolation[]
};

export const MOCK_HR_GENERAL_DATA = {
  totalHeadcount: 1018,
  retentionRate: 94.8,
  turnoverRate: 5.2,
  byDepartment: [
    { name: 'Nông Trường 1 (Bình Phước)', count: 320, ratio: '31.4%', color: '#ea580c' },
    { name: 'Nông Trường 3 (Tây Ninh)', count: 380, ratio: '37.3%', color: '#3b82f6' },
    { name: 'Nông Trường 2 (Bình Dương)', count: 240, ratio: '23.6%', color: '#10b981' },
    { name: 'Khối Văn Phòng & Kỹ Thuật', count: 45, ratio: '4.4%', color: '#8b5cf6' },
    { name: 'Phòng HCTH & Tài Chính', count: 33, ratio: '3.3%', color: '#f59e0b' },
  ],
  byAge: [
    { range: '18 - 25 tuổi', count: 185, percent: 18.2, color: '#38bdf8' },
    { range: '26 - 35 tuổi', count: 462, percent: 45.4, color: '#ea580c' },
    { range: '36 - 45 tuổi', count: 265, percent: 26.0, color: '#10b981' },
    { range: 'Trên 45 tuổi', count: 106, percent: 10.4, color: '#a855f7' },
  ],
  fluctuations: {
    newHires: 42,
    resigned: 18,
    transferred: 14,
    promoted: 9,
  },
  aiForecast: {
    riskPlantations: 'Nông trường 2 cần bổ sung 15 công nhân cạo mủ trước mùa thu hoạch cao điểm Q4',
  }
};

export const MOCK_RECRUITMENT_REPORT_DATA = {
  totalTarget: 85,
  totalHired: 72,
  hiringRate: 84.7,
  avgTimeToHireDays: 14,
  costPerHiredCandidate: 1784722,
  byDepartmentNeeds: [
    { dept: 'Nông Trường 1', target: 30, hired: 28, rate: '93.3%' },
    { dept: 'Nông Trường 3', target: 35, hired: 30, rate: '85.7%' },
    { dept: 'Nông Trường 2', target: 15, hired: 10, rate: '66.7%' },
    { dept: 'Khối Văn Phòng & HR', target: 5, hired: 4, rate: '80.0%' },
  ],
  candidateSources: [
    { source: 'Giới thiệu nội bộ', count: 184, hired: 42, percent: 58.3 },
    { source: 'Ngày hội tuyển dụng địa phương', count: 96, hired: 18, percent: 25.0 },
    { source: 'Mạng xã hội & Zalo tuyển dụng', count: 68, hired: 8, percent: 11.1 },
    { source: 'Website & Cổng tuyển dụng 1HRM', count: 42, hired: 4, percent: 5.6 },
  ],
  conversionFunnel: [
    { stage: '1. Tiếp nhận hồ sơ (Applied)', count: 390 },
    { stage: '2. Sơ loại tay nghề & Khám SK', count: 245 },
    { stage: '3. Phỏng vấn & Thử tay nghề', count: 128 },
    { stage: '4. Thử việc tại nông trường', count: 86 },
    { stage: '5. Ký hợp đồng chính thức', count: 72 },
  ]
};

export const MOCK_INCOME_PAYROLL_DATA = {
  totalPayrollMonth: 12850000000,
  avgIncomePerWorker: 12620000,
  growthComparedToLastMonth: 4.8,
  byPlantationComparison: [
    { name: 'Nông Trường 1 (Bình Phước)', workers: 320, payroll: 4160000000, avgIncome: 13000000, latexTons: 485.2 },
    { name: 'Nông Trường 3 (Tây Ninh)', workers: 380, payroll: 4788000000, avgIncome: 12600000, latexTons: 540.8 },
    { name: 'Nông Trường 2 (Bình Dương)', workers: 240, payroll: 2976000000, avgIncome: 12400000, latexTons: 362.0 },
    { name: 'Khối Văn Phòng Tổng Cty', workers: 78, payroll: 926000000, avgIncome: 11870000, latexTons: 0 },
  ],
  deductions: {
    totalSocialInsurance: 1349250000,
    totalPitTaxNewLaw: 245000000,
  }
};
